options:
    run-as:
        default: 'ubuntu'
        description:
            User as which to run the scripts
        type: string
    github-username:
        default: ''
        description: Username for github API
        type: string
    github-password:
        default: ''
        description: Password for github API
        type: string
    ga-dashboard-view-id:
        default: ''
        description: Google Analytics view ID for conjure-up
        type: string
    ga-dashboard-credentials:
        default: ''
        description:
            Base64-encoded Google Analytics account credentials for conjure-up in JSON format
        type: string
    ga-dashboard-credentials-file:
        default: '/home/ubuntu/.conjure-up-kpi/ga-dashboard.credentials'
        description:
            Where to place the Google Analytics credentials file for conjure-up
        type: string
